# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'all-in-one_classifier.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(556, 345)
        self.classifierTab = QtWidgets.QWidget()
        self.classifierTab.setObjectName("classifierTab")
        self.srcEdit = QtWidgets.QLineEdit(self.classifierTab)
        self.srcEdit.setGeometry(QtCore.QRect(128, 9, 321, 25))
        self.srcEdit.setObjectName("srcEdit")
        self.actorRb = QtWidgets.QRadioButton(self.classifierTab)
        self.actorRb.setGeometry(QtCore.QRect(9, 40, 63, 23))
        self.actorRb.setChecked(True)
        self.actorRb.setObjectName("actorRb")
        self.srcPath = QtWidgets.QLabel(self.classifierTab)
        self.srcPath.setGeometry(QtCore.QRect(9, 9, 109, 17))
        self.srcPath.setObjectName("srcPath")
        self.browseBtn = QtWidgets.QPushButton(self.classifierTab)
        self.browseBtn.setGeometry(QtCore.QRect(463, 9, 80, 25))
        self.browseBtn.setObjectName("browseBtn")
        self.msgOutput = QtWidgets.QLabel(self.classifierTab)
        self.msgOutput.setGeometry(QtCore.QRect(10, 70, 113, 17))
        self.msgOutput.setObjectName("msgOutput")
        self.labelRb = QtWidgets.QRadioButton(self.classifierTab)
        self.labelRb.setGeometry(QtCore.QRect(78, 40, 62, 23))
        self.labelRb.setObjectName("labelRb")
        self.msgBox = QtWidgets.QTextBrowser(self.classifierTab)
        self.msgBox.setGeometry(QtCore.QRect(9, 93, 441, 181))
        self.msgBox.setObjectName("msgBox")
        self.clearBtn = QtWidgets.QPushButton(self.classifierTab)
        self.clearBtn.setGeometry(QtCore.QRect(460, 220, 80, 25))
        self.clearBtn.setObjectName("clearBtn")
        self.execBtn = QtWidgets.QPushButton(self.classifierTab)
        self.execBtn.setGeometry(QtCore.QRect(460, 170, 80, 25))
        self.execBtn.setObjectName("execBtn")
        TabWidget.addTab(self.classifierTab, "")
        self.queryTab = QtWidgets.QWidget()
        self.queryTab.setObjectName("queryTab")
        self.gridLayout = QtWidgets.QGridLayout(self.queryTab)
        self.gridLayout.setObjectName("gridLayout")
        self.queryCancelBtn = QtWidgets.QPushButton(self.queryTab)
        self.queryCancelBtn.setObjectName("queryCancelBtn")
        self.gridLayout.addWidget(self.queryCancelBtn, 10, 2, 1, 1)
        self.queryResultText = QtWidgets.QLabel(self.queryTab)
        self.queryResultText.setObjectName("queryResultText")
        self.gridLayout.addWidget(self.queryResultText, 8, 0, 1, 1)
        self.recordCountNumber = QtWidgets.QLabel(self.queryTab)
        self.recordCountNumber.setObjectName("recordCountNumber")
        self.gridLayout.addWidget(self.recordCountNumber, 4, 1, 1, 1)
        self.searchKeywordsTextBox = ClickableLineEdit(self.queryTab)
        self.searchKeywordsTextBox.setObjectName("searchKeywordsTextBox")
        self.gridLayout.addWidget(self.searchKeywordsTextBox, 0, 1, 1, 1)
        self.searchKeywordsLabel = QtWidgets.QLabel(self.queryTab)
        self.searchKeywordsLabel.setObjectName("searchKeywordsLabel")
        self.gridLayout.addWidget(self.searchKeywordsLabel, 0, 0, 1, 1)
        self.queryResultClearBtn = QtWidgets.QPushButton(self.queryTab)
        self.queryResultClearBtn.setObjectName("queryResultClearBtn")
        self.gridLayout.addWidget(self.queryResultClearBtn, 11, 2, 1, 1)
        self.recordsCountLabel = QtWidgets.QLabel(self.queryTab)
        self.recordsCountLabel.setObjectName("recordsCountLabel")
        self.gridLayout.addWidget(self.recordsCountLabel, 4, 0, 1, 1)
        self.queryResultTextBox = QtWidgets.QTextBrowser(self.queryTab)
        self.queryResultTextBox.setObjectName("queryResultTextBox")
        self.gridLayout.addWidget(self.queryResultTextBox, 8, 1, 4, 1)
        self.queryBtn = QtWidgets.QPushButton(self.queryTab)
        self.queryBtn.setObjectName("queryBtn")
        self.gridLayout.addWidget(self.queryBtn, 0, 2, 1, 1)
        self.actorRadioBtn = QtWidgets.QRadioButton(self.queryTab)
        self.actorRadioBtn.setEnabled(True)
        self.actorRadioBtn.setChecked(False)
        self.actorRadioBtn.setObjectName("actorRadioBtn")
        self.gridLayout.addWidget(self.actorRadioBtn, 3, 1, 1, 1)
        self.titleRadioBtn = QtWidgets.QRadioButton(self.queryTab)
        self.titleRadioBtn.setChecked(True)
        self.titleRadioBtn.setObjectName("titleRadioBtn")
        self.gridLayout.addWidget(self.titleRadioBtn, 3, 0, 1, 1)
        TabWidget.addTab(self.queryTab, "")
        self.updaterTab = QtWidgets.QWidget()
        self.updaterTab.setObjectName("updaterTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.updaterTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dirList = QtWidgets.QListWidget(self.updaterTab)
        self.dirList.setObjectName("dirList")
        self.gridLayout_2.addWidget(self.dirList, 5, 0, 1, 4)
        self.statusContent = QtWidgets.QLabel(self.updaterTab)
        self.statusContent.setWordWrap(True)
        self.statusContent.setObjectName("statusContent")
        self.gridLayout_2.addWidget(self.statusContent, 8, 0, 1, 1)
        self.addedDirText = QtWidgets.QLabel(self.updaterTab)
        self.addedDirText.setObjectName("addedDirText")
        self.gridLayout_2.addWidget(self.addedDirText, 3, 0, 1, 2)
        self.mediaDirLabel = QtWidgets.QLabel(self.updaterTab)
        self.mediaDirLabel.setObjectName("mediaDirLabel")
        self.gridLayout_2.addWidget(self.mediaDirLabel, 0, 0, 1, 1)
        self.dirBrowseBtn = QtWidgets.QPushButton(self.updaterTab)
        self.dirBrowseBtn.setObjectName("dirBrowseBtn")
        self.gridLayout_2.addWidget(self.dirBrowseBtn, 1, 3, 1, 1)
        self.updateProgressBar = QtWidgets.QProgressBar(self.updaterTab)
        self.updateProgressBar.setProperty("value", 0)
        self.updateProgressBar.setObjectName("updateProgressBar")
        self.gridLayout_2.addWidget(self.updateProgressBar, 8, 2, 1, 2)
        self.dirTextBox = ClickableLineEdit(self.updaterTab)
        self.dirTextBox.setObjectName("dirTextBox")
        self.gridLayout_2.addWidget(self.dirTextBox, 0, 1, 1, 3)
        self.statusLabel = QtWidgets.QLabel(self.updaterTab)
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout_2.addWidget(self.statusLabel, 6, 0, 1, 1)
        self.clearDirListBtn = QtWidgets.QPushButton(self.updaterTab)
        self.clearDirListBtn.setObjectName("clearDirListBtn")
        self.gridLayout_2.addWidget(self.clearDirListBtn, 3, 3, 1, 1)
        self.addDirBtn = QtWidgets.QPushButton(self.updaterTab)
        self.addDirBtn.setObjectName("addDirBtn")
        self.gridLayout_2.addWidget(self.addDirBtn, 3, 2, 1, 1)
        self.updateBtn = QtWidgets.QPushButton(self.updaterTab)
        self.updateBtn.setObjectName("updateBtn")
        self.gridLayout_2.addWidget(self.updateBtn, 6, 2, 1, 1)
        self.cancelUpdateBtn = QtWidgets.QPushButton(self.updaterTab)
        self.cancelUpdateBtn.setObjectName("cancelUpdateBtn")
        self.gridLayout_2.addWidget(self.cancelUpdateBtn, 6, 3, 1, 1)
        TabWidget.addTab(self.updaterTab, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "JAV Tool"))
        self.actorRb.setText(_translate("TabWidget", "Actor"))
        self.srcPath.setText(_translate("TabWidget", "Source Location"))
        self.browseBtn.setText(_translate("TabWidget", "Browse"))
        self.msgOutput.setText(_translate("TabWidget", "Message Output"))
        self.labelRb.setText(_translate("TabWidget", "Title"))
        self.clearBtn.setText(_translate("TabWidget", "Clear"))
        self.execBtn.setText(_translate("TabWidget", "Execute"))
        TabWidget.setTabText(TabWidget.indexOf(self.classifierTab), _translate("TabWidget", "JAV Classifier"))
        self.queryCancelBtn.setText(_translate("TabWidget", "Cancel"))
        self.queryResultText.setText(_translate("TabWidget", "Result"))
        self.recordCountNumber.setText(_translate("TabWidget", "0"))
        self.searchKeywordsLabel.setText(_translate("TabWidget", "Search Keywords"))
        self.queryResultClearBtn.setText(_translate("TabWidget", "Clear"))
        self.recordsCountLabel.setText(_translate("TabWidget", "Total Records Found : "))
        self.queryBtn.setText(_translate("TabWidget", "Query"))
        self.actorRadioBtn.setText(_translate("TabWidget", "Actor"))
        self.titleRadioBtn.setText(_translate("TabWidget", "Title"))
        TabWidget.setTabText(TabWidget.indexOf(self.queryTab), _translate("TabWidget", "Media Query"))
        self.statusContent.setText(_translate("TabWidget", "Idle"))
        self.addedDirText.setText(_translate("TabWidget", "Added Directory List"))
        self.mediaDirLabel.setText(_translate("TabWidget", "Media Directory"))
        self.dirBrowseBtn.setText(_translate("TabWidget", "Browse"))
        self.statusLabel.setText(_translate("TabWidget", "Status:"))
        self.clearDirListBtn.setText(_translate("TabWidget", "Clear"))
        self.addDirBtn.setText(_translate("TabWidget", "Add"))
        self.updateBtn.setText(_translate("TabWidget", "Update"))
        self.cancelUpdateBtn.setText(_translate("TabWidget", "Cancel"))
        TabWidget.setTabText(TabWidget.indexOf(self.updaterTab), _translate("TabWidget", "Database Updater"))

from ClickableLineEdit import ClickableLineEdit

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())

